// <auto-generated />
namespace HomeTextileApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EmpAddPermanentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpAddPermanentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907230636148_Emp-Add-Permanent-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
