// <auto-generated />
namespace HomeTextileApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WorkerTAU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkerTAU));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251006003_Worker-TA-U"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
